MatmaRex/patchdemo

createwiki.sh

If any of the worktrees have been moved or deleted, 'add' will
fail unless a 'prune' is done first.

Do a 'worktree prune' before an add

---

new.php

The '/related' endpoint returns nothing if the change has no related
changes, so we weren't parsing Depends-On in changes that didn't have
direct dependencies.

Fix fetching changes via Depends-On

---

composer.json
includes.php
new.php

Use the V+2 check first because that is quicker, but if it
fails check the uploader's email against the trusted user
whitelist.
Fixes #51

Allow trusted users to create patches without V+2

---

new.php

The mostly likely failure scenario is that the user inputted patches that can't be merged, so do this first so the error (1) displays sooner and (2) is shown at the top of the page.

Query patch metadata first when creating

---

repositories.txt

GlobalWatchlist extension is being developed for use on WMF wikis, and it uses the GuidedTour extension when available

Add GlobalWatchlist and GuidedTour extensions

---

repositories.txt

Without EventLogging the GuidedTour extension doesn't work (reported at https://phabricator.wikimedia.org/T264145)
Follow-up to #124.

Add EventLogging extension

---

composer.json
config.default.php
index.php
new.php

Post links to Phabricator

---

index.php

It's the name of the Git remote and not relevant here at all.

Remove 'origin/' prefix from the branches dropdown

---

setup.sh

The script was not executed, because it did not pass the "sanity
checks": https://stackoverflow.com/a/43454485
>   the files under these directories have to be pass some sanity checks
>   including the following: be executable, be owned by root, not be
>   writable by group or other and, if symlinks, point to files owned by
>   root. Additionally, the file names must conform to the filename
>   requirements of run-parts: they must be entirely made up of letters,
>   digits and can only contain the special signs underscores ('_') and
>   hyphens ('-'). Any file that does not conform to these requirements
>   will not be executed by run-parts. For example, any file containing
>   dots will be ignored.
Furthermore, because it was a symlink, the actual script would not
correctly detect the …

Fix the Cron job to deduplicate files

---

setup.sh

I ran this manually recently and it freed ~1.8 GB of disk space
with ~120 wikis existing.
https://app.slack.com/client/T024KLHS4/GUBD17GUQ/thread/GUBD17GUQ-1603310513.015800 (eww, Slack)

Add Cron job to optimize databases

---

deletewiki.sh

The command can sometimes be executed when the database is not yet created, currently this spits out errors because non-existing database cannot be deleted.

Add `if exists` guard to DROP DATABASE command

---

new.php

Use htmlentities when escaping link label

---

LocalSettings.txt

No longer the default following [1], but would be helpful on patchdemo. Results in extra information being sent to the console log.
[1] https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/GlobalWatchlist/+/17ba0e3315e1d48215c885f065fedb503f454404

[config] set $wgGlobalWatchlistDevMode to true

---

includes.php
new.php

Uses the 'announcedTasks' db column to ensure we only
announce on tasks that got the creation announcement.
Fixes #188

Announce when wikis are deleted

---

editcounts.php

We already handle missing data in the table, and the
DB might not exist if the wiki didn't setup correctly.

editcounts: Don't error if DB not found

---

config.default.php
includes.php

Doesn't make sense to have any restrictions on a
private installation. Just allow all users to do
everything.

Fix authentication functions for private installs

---

LocalSettings-proxy.txt
index.php
new.php
new/postinstall.sh
pages-proxy/Common.js.xml

Untested, but I'd like to add a proxy checkbox for testing languages as part of the desktop improvements project. It's really hard to test these without and I've been having to workaround this by using https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MobileFrontend/+/641808

Allow use of the Mobilefrontend content provider proxy

---

css/common.css
delete.php
editcounts.php
index.php
new.php

This makes URLs and other things a bit cleaner by not
using all 32 characters.
16^10 is still a trillion, so unlikely to cause a collision.
Truncate the display of older hashes so they look consistent.

Use a 10 character hash for wiki names

---

css/common.css

OOUI sets display to block, when it should be list-item.

Fix display of marker on <summary> tag

---

index.php

We already cast null to [] elsewhere, so use it here.
Fixes #288

PatchSelectWidget: Use sanitized patch list data

---

repositories.txt

Doesn't add DjVu support for now, because PDFs should be enough
for current testing requirements.

Add ProofreadPage to supported extensions

---

localsettings/extensions-GrowthExperiments.txt
pages/GrowthExperiments.txt
pages/GrowthExperiments.xml

Use static task suggester for suggested edits, and include content for
two article pages and link suggestions for one of those articles.
Bug: T280664

GrowthExperiments: Link suggestion support

---

localsettings/feature-proxy.txt

RelatedArticles, Page previews and Vector all have additional configuration
which can be made use of to aid testing against production articles
so let's use them.
This unblocks us testing a few things on the page previews site.

Expand article proxying to other features

---

localsettings/feature-proxy.txt
new.php
repositories.txt

Add the extension to the list but only enable it if proxy
is set or its added in the dropdown.
Drop configuration variables as these are all the defaults
in the new extension.
Should not be merged until https://gerrit.wikimedia.org/r/c/mediawiki/extensions/MobileFrontend/+/709544
has been merged.

Use the new MobileFrontendContentProvider

---

pages/Disambiguator.txt
pages/Disambiguator.xml
repositories.txt

This is deployed to nearly all WMF wikis. Community Tech is actively working on it and it'd be useful to have it available on Patch Demo.

Add Disambiguator extension

---

pages/Disambiguator.xml

The actual dab page was missing the `__DISAMBIG__` magic word

Fix test page for Disambiguator extension

---

repositories.txt

WMF deployed extension that should be available to test.
Already included in repositories-preset-wikimedia.txt but not actually available in the list of supported extensions.

Add RevisionSlider to allowed extensions

---

api.php

This shouldn't happen, but don't throw an uncaught error if it does.

api.php: Check patch query string is present

---

js/index.js
js/new.js

There's no reason for this preference to not persist
across multiple sessions.

Store notification toggle state in localStorage

---

repository-lists/all.txt

By default it uses external services, like we do with Citoid.
Part of #316

Enable Math extension

---

setup.sh

`npm install` will always re-write package-lock.json, even if there
were no changes in package.json, which is very annoying when you're
running significantly different versions of NPM locally and in
production, since their package-lock.json output will differ and so
production will have unstaged changes after the setup.
`npm ci` doesn't do that. I didn't know about it before.
https://docs.npmjs.com/cli/v8/commands/npm-ci

Replace `npm install` with `npm ci` in the setup script

---

css/common.css
index.php
js/index.js
localsettings/extensions-GrowthExperiments.txt
localsettings/extensions-PageViewInfo.txt
localsettings/feature-proxy.txt
new.php
new/install.sh
new/postinstall.sh
pages-proxy/Common.js.xml

Put in some simple validation to limit language codes
to letters and hyphens for security, but don't bother
to check the code is valid.
Fixes #361

Allow users to change $wgLanguageCode

---

localsettings/core.txt
new/postinstall.sh

Warnings can be produced by maintenance scripts, e.g. when trying to build REL1_30. Ignore these when getting the main page title.

Main Page title: Ignore PHP warnings in output of eval.php

---

new/install.sh

Currently this works because 'core' comes before
'extension'/'feature' etc. in the alphabet, but
that is a nasty bug waiting to happen.

Ensure core.php is always loaded first

---

new/postinstall.sh

Various errors have caused this script to fail, but it
isn't critical, so let the wiki continue to install so
the error can be better debugged.
Part of #385

Don't abandon a wiki if the main page wasn't edited

---

new/postinstall.sh
pages/extensions-WikiLambda.txt
pages/extensions-WikiLambda.xml

* Edit mainpage after import to use this new title
* Use getPrefixedText to include the namespace
Fixes #385

WikiLambda: Change 'mainpage' message to point to Project namespace

---

repository-lists/wikimedia.yaml

GrowthExperiments is now on almost all Wikipedias https://phabricator.wikimedia.org/T247507#7405750

Add GrowthExperiments to wikimedia group

---

.gitignore
composer.lock
new.php
new/composerinstall.sh
repository-lists/composerinstall.yaml
setup.sh

The former respects `composer.lock` files if they exist, as is
recommended by https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control,
and is the command given in installation instructions, e.g.
https://www.mediawiki.org/wiki/Extension:TemplateStyles
Add the composer.lock for Patch demo itself.

Use `composer install` instead of `composer update`

---

repository-lists/wikimedia.yaml

Reverts MatmaRex/patchdemo#411 as fixed upstream by https://gerrit.wikimedia.org/r/c/mediawiki/extensions/GrowthExperiments/+/752711
Part of #408

Revert "Temporarily remove GrowthExperiments from wikimedia.yaml"

---

repository-lists/all.txt

GlobalPreferences is available on most Wikimedia sites, and I have a bunch of patches want to show to the public.
It has code paths for using the database of a local wiki, and it can work without CentralAuth according to my test.

Support GlobalPreferences extension

---

localsettings/extensions-GlobalBlocking.php
repository-lists/all.txt

Enables the [GlobalBlocking](https://www.mediawiki.org/wiki/Extension:GlobalBlocking) extension on Patch Demo.
GlobalBlocking is in use in WMF wikis and recently it has started to receive many patches. It'd be great to test them in a test environment before they even reach e.g. the Beta Cluster or Production wikis.

Add GlobalBlocking extension

---

css/common.css
index.php

* Use a multi-column layout (4 on desktop)
* Use a smaller font size
* Remove 'mediawiki/' and 'mediawiki/extensions' prefixes

Compact repo list

---

index.php
js/index.js
localsettings/extensions-GrowthExperiments.php
new.php
repository-lists/all.txt

Makes performance much better and supports most the important
features of InstantCommmons.
When selected, $wgInstantCommons is disabled and the extension
is installed instead (per the instructions on MediaWiki).

Provide QuickInstantCommons as a (default) option

---

new.php
new/postinstall.sh
repository-lists/all.txt
repository-lists/wikimedia.yaml

Similar to OOUI, except it's JS only, no PHP.
Also add support for 'main' as an alias for the 'master' branch.
Without this, installing Codex fails, because it doesn't have a
branch named 'master'.

Build Codex from source if repo is included

---

repository-lists/all.txt

This extension is not deployed, but it aids in testing Codex in a
MediaWiki environment.

Add VueTest extension

---

setup.sh

Running "npm run build" in Codex breaks with Node 12, but works with
Node 14.

Install Node 14 instead of Node 12

---

localsettings/extensions-Score.php
repository-lists/all.txt
repository-lists/wikimedia.yaml

Ensure we don't try to use LilyPond as it isn't safe
without a secure sandbox, but we can test the VE UI.
Part of #316

Partially enable Extension:Score

---

new/checkout.sh

Fix `git worktree` creating invalid refs

---

new/precheckout.sh

Without this, the readlink fix for #446 breaks when Codex or OOUI is
included, because it tries to do
readlink -f $PATCHDEMO/wikis/$NAME/build/codex , but the parent
directory doesn't exist.

Create the w/build/ directory in precheckout.sh

---

repository-lists/all.txt

Enables the [CampaignEvents](https://www.mediawiki.org/wiki/Extension:CampaignEvents) extension on Patch Demo.
CampaignEvents extension is being created by the [Campaigns Team](https://meta.wikimedia.org/wiki/Campaigns/Foundation_Product_Team). It'd be great to test it in a test environment before they even reach e.g. the Beta Cluster or Production wikis.

Adding Campaign Events Extension

---

new/checkout.sh
new/precheckout.sh

This avoids errors when trying to check things out into /w/build/FOO.
Also remove the line in precheckout.sh creating /build. This is the
wrong path, it should be /w/build, but creating that causes errors
because the "git worktree add" command wants an empty directory.

checkout.sh: Make sure path exists before readlink'ing it

---

repository-lists/all.txt

*Not* adding to wikimedia preset because its a big extension and only used on enwiki

enable PageTriage extension

---

repository-lists/all.txt

This has no special install requirements and is still in production.
It is going to be useful in Q1

Add WikiLove

---

oauth.php

If the server is down or OAuth isn't working, Patch demo
can still run without letting the user log in, instead of
stopping on an uncaught exception.

Handle OAuth server connection errors

---

pages/extensions-Phonos.xml

Larynx usually wants the slashes, so here we always include them.
We also only use 2-letter language codes because Larynx is limited in what it can interpret.
Some examples still don't work, especially those for unsupported languages, but this is enough for product/design to make use of Phonos on Patch Demo.

Phonos: improve example IPA on corpus page

---

new.php

Patches could affect the outcome of the installation
process, e.g. changing extension.json dependencies.

Apply patches before running installer

---

localsettings/extensions-MediaSearch.php
repository-lists/all.txt

Not enabled by default because this is only installed on Commons.
Configure to use external API results from Commons and WikiData,
per on-wiki instructions.
Fixes #487

Enable MediaSearch extension

---

css/common.css

OOUI moved to flexbox, so we need to enable flex-wrap.

Fix layout of form on mobile

---

repository-lists/all.txt

Currently getting "Repository mediawiki/extensions/GeoData not supported"
Mentioned in wikimedia but not all
(untested)

add support for Geodata

---

setup.sh

Without this, the Phonos test page was timing out on import
and causing wiki creation to fail.

Add system dependency on lame MP3 encoder for Phonos extension

---

pages/extensions-Phonos.xml

Phonos no longer uses a parser function.

Update Phonos examples to use new tag syntax

---

new.php

This link was correct everywhere else (e.g. on the generated Main Page content), but the link posted to Phabricator was wrong.

new.php: Fix link to Codex docs site

---

localsettings/feature-proxy.php

Introduced by https://gerrit.wikimedia.org/r/c/mediawiki/skins/Vector/+/838943. Normally we'd try for backwards compatibility here, but the old setting was broken anyway, so that's not needed.

Proxy feature: Use new $wgVectorSearchApiUrl setting

---

includes.php
index.php
repository-lists/minimal.yaml

It's too easy to accidentally create a wiki that is open to spam bots.

Add ConfirmEdit to 'minimal' preset

---

api.php
includes.php
index.php
new.php

Add API action 'findwikis' to find a wiki by a change number

---

repository-lists/all.txt
repository-lists/composerinstall.yaml

There is a maintenance script to add existing users, but I guess they won't exist before the extension is installed

Add AntiSpoof extension

---

new.php

This ensures spaces in URLs don't break them.

Use explicit URL syntax when posting to Phabricator

---

api.php

We need the API to emit `Access-Control-Allow-Origin: *` to allow downstream usage in JavaScript application. For example the integration with https://gerrit.wikimedia.org/. Without it, the browser complains with:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at
https://patchdemo.wmflabs.org/api.php?action=findwikis&change=922162. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Part of #285
Follow-up #537
Bug: https://phabricator.wikimedia.org/T332474

api.php: add CORS header

---

repository-lists/composerinstall.yaml

UrlShortener will soon have composer dependencies, i.e. https://gerrit.wikimedia.org/r/c/mediawiki/extensions/UrlShortener/+/930716

composerinstall.yaml: add UrlShortener

---

setup.sh

Used by some extensions, e.g. UrlShortener

Add php-gd as a dependency

---

new.php

Sometimes folks point 'Depends-On' entries to Wikimedia config repositories. We don't support them, but these dependencies are usually not needed to test a patch on Patch demo, so ignore them instead of erroring out.
Closes #573

Ignore dependencies on unknown repositories
