MatmaRex/patchdemo

- .gitignore
- applypatch.sh
- createwiki.sh
- deduplicate.sh
- new.php
- setup.sh
> Move all wikis to /wikis sub-folder

- createwiki.sh
- new.php
Also make all links relative to the current path.
Fixes #5
> Automatically detect server path

- deletewiki.sh
Command-line only for now
Part of #4
> Create deletewiki.sh script

- repositories.txt
> Add extensions/BetaFeatures

- new.php
> Add 'change:' prefix to gerrit API queries

- .gitignore
- .phpcs.xml
- composer.json
- config.default.json
- config.default.php
- createwiki.sh
- delete.php
- footer.html
- includes.php
- index.css
- index.php
- new.php
- oauth.php
When enabled, only authenticated users can create new wikis, and the creator of each wiki is stored and displayed in the list.
Fixes #25
> OAuth support

- LocalSettings.txt
> Disable ResourceLoader's localStorage cache

- includes.php
- index.css
Particularly useful when you want to come back from new.php.
> Link the logo to the main page

- includes.php
- index.css
- index.php
> Show patch title in table

- repositories.txt
> Add support for FlaggedRevs

- createwiki.sh
- includes.php
- index.php
> Store create time in a file

- repositories.txt
> Add CodeMirror extension

- createwiki.sh
- new.php
> Customise [[Main Page]]

- repositories.txt
> Add AbuseFilter to extensions

- LocalSettings.txt
> Enable InstantCommons

- repositories.txt
> Enable TimedMediaHandler

- LocalSettings.txt
See https://phabricator.wikimedia.org/T254349
> Fix VE default config

- repositories.txt
> Add Linter dependency, now required by DiscussionTools

- repositories.txt
Makes environment more production-like.
> Add ULS extension

- footer.html
- includes.php
- index.css
- oauth.php
Other minor tweaks:
* Centre login page so it aligns with OAuth screen
* Right align footer link
* Stretch table now that there is a sensible max width
> Layout: Use a fixed width layout

- LocalSettings.txt
Rather than "Patch Demo (123456,7):"
> Use "Project:" for the project namespace

- LocalSettings.txt
- createwiki.sh
- includes.php
- index.css
- index.js
- index.php
- new.php
> Choose extensions to use, validate branches

- .htaccess
- 404.php
- includes.php
- oauth.php
> Add custom 404 handler

- LocalSettings.txt
> Don't share cookies across wikis

- delete.php
- includes.php
- index.php
- new.php
> Delete files/databases when wiki fails to install fully

- includes.php
- index.php
- new.php
> Show linked tasks on main page

- index.css
- index.php
> Highlight merged/abandoned changes

- index.css
- new.js
- new.php
* Show a progress bar at the top of the page that increments
with each successful shell command.
* Show any error messages at the top of the page.
* Only give a wiki link when the wiki has been successfully built,
also show this at the top of the page. Make it a big blue button.
* Apply console styling to the log messages to make it clear they
are output for technical users.
> Make installer more user friendly

- index.js
- index.php
- new.php
- oauth.php
The diffs are huge because I wrapped a bunch of code in big if()-s, ignore whitespace when reviewing.
> Display the table of previously generated wikis when not signed in

- setup.sh
(I've already applied this on https://patchdemo.wmflabs.org/)
> Fix Parsoid/VisualEditor for pages with slashes in the title

- LocalSettings.txt
Required for testing UploadWizard (and plain uploads)
> Enable uploads

- README.md
> Add FAQ entry about running your own instance

- index.css
- index.js
- index.php
- De-indent table script block
- Add checkbox to filter only "closed" wikis
- Prompt users when they have closed wikis than can be deleted
Fixes #133
> Tell users when they have wikis containing only merged patches

- setup.sh
> Set session expiration to a month

- pages/Cite.txt
- pages/Cite.xml
- pages/Citoid.txt
- pages/Citoid.xml
Also move MediaWiki:Cite-tool-definition.json to Cite.xml
> Create test pages for citation needed feature

- createwiki.sh
> Grant FlaggedRevs editor rights to the default account

- index.css
With my font stack, 'Custom' wraps to the next line.
> Make form slightly wider so radio lists fits on more OSes

- createwiki.sh
> Run update script after installation

- deduplicate.sh
- new.php
- setup.sh
> Run deduplicate.sh as cron job

- .github/workflows/php.yml
Something strange happening with an update to PHP 8.
> Temporarily disable PHP CI

- LocalSettings.txt
This applies some CSS that makes environments
more production-like.
> Minerva: Enable MinervaApplyKnownTemplateHacks

- index.js
- package-lock.json
- package.json
* Remove hack fixed upstream
* Update devDependencies
> Update to OOUI 0.41

- new.php
This ensures the progress bar updates in a timely manner
> Flush the output buffer whenever progress changes

- new.js
- new.php
This ability was added upstream for this use case.
> Show progress bar as pending while wiki is being built

- index.php
Also remove unneeded ENT_QUOTES.
> Add 'title' to other links with ellipsed text in the wikis table

- config.default.php
- includes.php
- index.php
- new.php
> Move gerrit/phab URLs to config

- LocalSettings.txt
- repositories.txt
Deployed on many WMF wikis and currently being worked on by AHT team.
> Enable SecurePoll extension

- LocalSettings.txt
> Add an unintrusive anti-spam CAPTCHA

- editcounts.php
- includes.php
- Separate out a can_admin method
- Add edit count page for spam monitoring
> Add edit count page for spam monitoring

- includes.php
- new.php
> Use better check for HTTPS from $_SERVER

- new.php
> Use protocol-relative $wgServer for the wikis

- new.php
Reverts MatmaRex/patchdemo#216
> Revert "Use protocol-relative $wgServer for the wikis"

- delete.php
- index.css
Also tweak margins of consoleLog CSS
> Style log output on delete page

- .gitignore
- .phpcs.xml
- createwiki.sh
- delete.php
- editcounts.php
- includes.php
- index.php
- migrateToSql.php
- new.php
- setup.sh
- sql/.htaccess
- sql/patchdemo.sql
- sql/user.sql
> Store wiki cache in structured DB instead of flat file

- delete.php
- editcounts.php
- includes.php
- index.css
- index.php
- sql/patchdemo.sql
> Logically delete rows from wikis table

- index.js
Happens when login is disabled.
> Check widgets exist before trying to infuse

- repositories.txt
We already have TextExtracts and PageImages which are semi-optional dependencies.
> Add Popups extension

- createwiki.sh
- new.php
- postinstall.sh
> Run postinstall (including update.php) after applying patches

- delete.php
- includes.php
- index.php
- new.php
When I was writing it, we didn't have OAuth authentication, so this
wasn't worth the effort.
Simplest possible, inspired by the top StackOverflow result.
> Add anti-CSRF token to the main form

- index.css
- new.php
- postinstall.sh
* Alice & Bob are regular accounts, can test messaging etc.
* Mallory is indefinitely blocked.
> Create additional accounts for testing

- setup.sh
For example in Echo notifications.
> Install ImageMagick and rsvg for rendering SVG images

- LocalSettings.txt
- new/install.sh
> Use short URLs

- new/postinstall.sh
> Set dummy email addresses for test accounts

- new/postinstall.sh
This is a quick sketch of what'd probably work. I don't have patchdemo set up locally to test it properly.
> Set up for custom SQL being run for new wikis

- new/postinstall.sh
By default this imports interwikis from en.wiki
> Run the populateInterwiki maintenance script

- setup.sh
The default is not enough for the StopForumSpam extension. (#241)
> Increase PHP memory_limit

- repositories-preset-wikimedia.txt
- repositories.txt
https://phabricator.wikimedia.org/T271991
> Add StopForumSpam extension to patchdemo

- new.php
> Allow users to specify patchset numbers

- composer.json
- package-lock.json
- package.json
Contains TagMultiselectWidget fixes.
Also update eslint.
> Update OOUI to 0.41.2

- includes.php
Returns null when patch not found.
> Fix typehint of gerrit_query

- PatchSelectWidget.php
- api.php
- index.php
- js/PatchSelectWidget.js
- js/index.js
- new.php
Based on TagMultiselectWidget, shows the patch number and metadata when a valid patch is entered.
> Create a PatchSelectWidget

- api.php
- css/common.css
- includes.php
- index.php
- js/PatchSelectWidget.js
- js/index.js
- Avoid extra database queries when fetching wiki data
- PatchSelectWidget: Improve normalisation
- Warn when patch list matches an existing wiki
Fixes #196
> Warn when patch list matches an existing wiki

- LocalSettings.txt
This feature is enabled on WMF wikis
> Enable wgEchoPerUserBlacklist

- repositories.txt
Will make it easier to review and test patches
> Add ChessBrowser to supported extensions

- LocalSettings.txt
- repositories.txt
Will make it easier to test and review patches
> Add Wikispeech to supported extensions

- repositories.txt
It doesn't have any hard dependencies.
> Add Wikisource to supported extensions

- localsettings/extensions-VisualEditor.txt
> Enable visual diff on history page beta feature

- js/index.js
> Warn when creating a wiki with no patches

- css/common.css
- index.php
- js/index.js
- js/new.js
- new.php
> Notify users when wiki is ready

- localsettings/core.txt
This is enabled on all production wikis
> Enable watchlist expiry feature

- repositories.txt
For internal team demo and testing.
> Add Wikistories extension

- index.php
> Set empty actions cell after loop

- localsettings/extensions-ConfirmEdit.txt
> Don't show captcha to any logged in users

- includes.php
- new.php
The username "Patch Demo" would probably be annoying to
change at this point.
> Try to use consistent casing for "Patch demo"

- localsettings/core.txt
> Set legacy $wgLogo for older releases

- composer.json
- includes.php
> Don't use current PHP env when running shell commands

- new.php
- new/install.sh
- new/postinstall.sh
This allows us to drop the directory-exists checks.
> Only ever iterate over selected repos

- new/composerupdate.sh
> Check composer.json exists before update

- new.php
Lost during a logical conflict.
> Restore $reposString

- localsettings/extensions-UniversalLanguageSelector.php
Caused by a logical conflict during various merges.
> Convert ULS config to PHP

- new.php
- new/submodules.sh
> Run `git submodule update` on WikiLambda

- new.php
This allows us to cleanly delete the wiki if the connection
is closed. Previously the wiki would just be left half-created.
We can't just use register_shutdown_function as that could fire
during a shell command and delete the wiki while the command
is still running.
Fixes #332
> Regularly check the user connection status when creating a wiki

- localsettings/extensions-Translate.php
This is needed for Special:AggregateGroups to allow modification.
Fixes #404
> Add `translate-manage` user right to admins

- repository-lists/all.txt
> Enable Thanks extension

- repository-lists/wikimedia.yaml
> Temporarily remove GrowthExperiments from wikimedia.yaml

- setup.sh
> Add php-wikidiff2 to installation process

- new.php
> Always check out patched repos

- index.php
- js/PatchSelectWidget.js
- js/index.js
> Add 'copy' button to wikis

- config.default.php
- new.php
- new/postinstall.sh
- repository-lists/all.txt
- repository-lists/wikimedia.yaml
- setup.sh
> Build OOUI from source if repo is included

- new.php
Also add the link to the Phabricator announcement.
Fixes #432
> Add OOUI Demos link to Main_Page when patched

- localsettings/core.php
Matches the config on WMF wikis.
> Allow user JS & CSS

- index.php
- js/PatchSelectWidget.js
> Handle pasted Gerrit URLs

- new.php
Consistent with how this variable is named elsewhere
> Rename $namePath to $wiki

- includes.php
- migrateBranchesToSql.php
- migrateToSql.php
- new.php
Also throw errors if these are called from the command line
and create an is_cli method for that check.
Fixes #336
> Create get_server & get_server_path methods

- localsettings/extensions-Flow.php
- repository-lists/all.txt
- repository-lists/composerinstall.yaml
- repository-lists/wikimedia.yaml
> Enable Flow extension

- new.php
- new/postinstall.sh
And link it in the success message and on the Main Page, like we do with
OOUI.
Per discussion on #432.
> Deploy Codex demo to /w/build/codex/docs

- includes.php
e.g. https://gerrit.wikimedia.org/r/q/donotmerge
> "Do not merge" regex: Also match "donotmerge" without spaces

- js/PatchSelectWidget.js
Moving URL regex to getTagInfoFromInput so that URLs are always
matched even if a paste event doesn't fire (e.g. on some mobile IMEs).
> PatchSelectWidget: Improve URL input handling

- localsettings/core.php
This matches the config of all public WMF wikis.
> Core config: Set wgEditSubmitButtonLabelPublish to `true`

- repository-lists/all.txt
> Enable cldr extension

- delete.php
- editcounts.php
- includes.php
- index.php
- new.php
- sql/patchdemo.sql
> Allow users to set the landing page when creating a wiki

- ComboBoxInputWidget.php
- includes.php
- index.php
- js/index.js
...and suggest known pages titles.
> Convert "Landing page" input to a ComboBoxInputWidget

- repository-lists/all.txt
> Add WikimediaIncubator extension

- repository-lists/all.txt
This was already in wikimedia.yaml, but not here.
Fixes #508
> all: Add WikimediaMessages

- localsettings/extensions-ContactPage.php
- repository-lists/all.txt
> Add ContactPage

- localsettings/extensions-WikiEditor.php
https://mediawiki.org/wiki/Extension:WikiEditor#Realtime_Preview
> Enable the Realtime Preview feature (WikiEditor)

- index.php
- localsettings/feature-tempuser.php
- new.php
- new/postinstall.sh
> Allow enabling temp user creation for IP Masking QA

- localsettings/feature-proxy.php
Depends on https://gerrit.wikimedia.org/r/q/I8441eec9ec5d10c7c09dc6e0ba909ad564db621f
Fixes #528
> Fix article paths when proxying

- includes.php
- index.php
- new.php
- new/install.sh
> Make Vector 2022 the default skin for branches after origin/wmf/1.40.0-wmf.19

- localsettings/extensions-CheckUser.php
This allows testing IP Masking workflows on Patch Demo.
> Assign checkuser-temporary-account to checkuser group

- setup.sh
> Upgrade to Node 16

- new/submodules.sh
> submodules: Only run in non-empty folders

- new.php
> Show a warning when posting to Phab fails, instead of abandoning

- new.php
It was trying to output a <script></script> inside another <script></script>, which won't work without extra special escaping, but the entire thing can be simplified.
> Fix ability to bypass V+2 verification

- localsettings/services-parsoid.php
> Fix developer setup of Parsoid after changes in MediaWiki

- includes.php
> Avoid PHP notices for private/non-existing Phab tasks

- repository-lists/all.txt
> Add UrlShortener

- includes.php
- index.php
- js/index.js
- new.php
- sql/patchdemo.sql
This value is displayed, and used when a wiki is copied.
Fixes #519
> Store which repos/preset is used when creating a wiki

- api.php
- css/common.css
- editcounts.php
- includes.php
- index.php
- js/index.js
- new.php
- sql/patchdemo.sql
> Mark when wikis are still being built

- new.php
Patches could change composer dependencies
> Check out patches before running `composer install`

- new.php
> A bit of code cleanup

- repository-lists/all.txt
Bug: [T340198](https://phabricator.wikimedia.org/T340198)
> Rename IncidentReporting -> ReportIncident

- deduplicate.sh
> Wipe the localisation cache for all wikis daily
